name        : libpcap
version     : 1.3.0
release     : 2
source      :
    - http://www.tcpdump.org/release/libpcap-1.3.0.tar.gz : 41cbd9ed68383afd9f1fda279cb78427d36879d9e34ee707e31a16a1afd872b9
homepage    : http://www.tcpdump.org
license     : BSD
component   : system.utils
summary     : packet capture library
description : |
    libpcap is a library that provides a high level interface to packet capture systems. It is capable of accessing all packets the network, including those destined for other hosts.
patterns    :
    - devel: [/usr/share/man/man3, /usr/share/man/man5]
emul32      : yes
builddeps   :
    - bison-32bit-devel
    - flex-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
