name       : libpcap
version    : 1.9.0
release    : 6
source     :
    - https://www.tcpdump.org/release/libpcap-1.9.0.tar.gz : 2edb88808e5913fdaa8e9c1fcaf272e19b2485338742b5074b9fe44d68f37019
homepage   : https://www.tcpdump.org
license    : BSD-3-Clause
component  : system.utils
summary    : A system-independent interface for user-level packet capture
description: |
    libpcap is a library that provides a high level interface
    to packet capture systems. It is capable of accessing all packets
    the network, including those destined for other hosts.
patterns   :
    - devel : [/usr/share/man/man3, /usr/share/man/man5]
emul32     : yes
builddeps  :
    - pkgconfig(bluez)
    - bison-32bit-devel
    - flex-32bit-devel
setup      : |
    sed -i -e 's|-fpic|-fPIC|g' configure
    %configure --enable-ipv6
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/%libdir%/*.a
