name       : libpcap
version    : 1.8.1
release    : 3
source     :
    - https://www.tcpdump.org/release/libpcap-1.8.1.tar.gz : 673dbc69fdc3f5a86fb5759ab19899039a8e5e6c631749e48dcd9c6f0c83541e
homepage   : http://www.tcpdump.org
license    : BSD-3-Clause
component  : system.utils
summary    : A system-independent interface for user-level packet capture
description: |
    libpcap is a library that provides a high level interface
    to packet capture systems. It is capable of accessing all packets
    the network, including those destined for other hosts.
patterns   :
    - devel : [/usr/share/man/man3, /usr/share/man/man5]
emul32     : yes
builddeps  :
    - pkgconfig(bluez)
    - bison-32bit-devel
    - flex-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --enable-ipv6
build      : |
    %make
install    : |
    %make_install
